### ISSUE TITLE
Issues when placed inside Drawer

### ISSUE THREAD

**Issue by Aol1234** [tejainece/bidirectional_scroll#1]
Is there a way to place the scroller inside the drawer without its contents overflowing into the rest of the screen?

![image](https://github.com/tejainece/bidirectional_scroll/assets/35489905/9febb8cb-47b9-48cd-99e4-78f73a7b0cd4)

Also I received a setState() error when drawer is re-opened after it is closed the first time.

`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: setState() called after dispose():` `_ScrollViewportState#63a41(lifecycle state: defunct, not mounted)`
`This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.`
`The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().`
`#0      State.setState.<anonymous closure>   framework.dart:1106`
`#1      State.setState   framework.dart:1141`
`#2      _ScrollViewportState.initState.<anonymous closure>  viewport.dart:56`
``#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)``
``#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)``
``#5      _DelayedData.perform (dart:async/stream_impl.dart:515:14)``
``#6      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)``
``#7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)``
``#8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)``
`#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)`

**Comment by tejainece** [comment]
Can you please share a very minimal code to reproduce this issue?
